"""
Incident report generation.

Builds a Markdown report entirely from persisted, real data for the given
incident: no template placeholders are left in the final text, and no
field is invented — if something wasn't computed (e.g. no analyst
questions were asked), the report says so explicitly.
"""

from __future__ import annotations

from datetime import datetime, timezone

from database import db as dbmod
from rag.context_builder import scenario_name_to_key
from rag.next_stage import get_next_stage
from simulation.scenarios import SCENARIOS


def generate_report_markdown(incident_id: str) -> str:
    incident = dbmod.get_incident(incident_id)
    if not incident:
        raise ValueError(f"Unknown incident: {incident_id}")

    sim = dbmod.get_simulation(incident["sim_id"])
    events = dbmod.get_events(incident["sim_id"])
    findings = dbmod.get_findings(incident["sim_id"])
    qa_history = dbmod.get_qa_history(incident_id)
    scenario_key = scenario_name_to_key(incident["scenario"])
    next_stage = get_next_stage(scenario_key)
    scenario_desc = SCENARIOS.get(scenario_key, {}).get("description", "")

    lines: list[str] = []
    lines.append(f"# Incident Report — {incident_id}")
    lines.append("")
    lines.append(f"*Generated: {datetime.now(timezone.utc).isoformat(timespec='seconds')}*")
    lines.append("")
    lines.append("> This report describes a **simulated** security incident generated by "
                  "ShadowTrace AI for training/demonstration purposes. No real systems, "
                  "accounts, or data were involved.")
    lines.append("")

    lines.append("## Summary")
    lines.append(f"- **Scenario:** {incident['scenario']} — {scenario_desc}")
    lines.append(f"- **Severity:** {incident['severity']} (score {incident['severity_score']})")
    lines.append(f"- **Status:** {incident['status']}")
    lines.append(f"- **Affected user:** {incident.get('affected_user')}")
    lines.append(f"- **Affected resources:** {', '.join(incident.get('affected_resources', [])) or 'none recorded'}")
    lines.append(f"- **Simulation ID:** {incident['sim_id']}")
    lines.append(f"- **Created:** {incident['created_at']}")
    lines.append("")

    lines.append("## Timeline")
    lines.append("| Time | Event Type | Action | Resource | Status |")
    lines.append("|---|---|---|---|---|")
    for e in events:
        ts = e["timestamp"].split("T")[-1][:8]
        lines.append(f"| {ts} | {e['event_type']} | {e['action']} | {e.get('resource') or '-'} | {e['status']} |")
    lines.append("")

    lines.append("## Detection Findings (Evidence)")
    if findings:
        for f in findings:
            lines.append(f"### {f['rule_name']}")
            lines.append(f"- **Description:** {f['description']}")
            lines.append(f"- **Severity contribution:** +{f['severity_points']}")
            lines.append(f"- **Related technique label:** {f.get('technique') or 'n/a'}")
            lines.append(f"- **Evidence event IDs:** {', '.join(f['evidence'])}")
            lines.append("")
    else:
        lines.append("No deterministic detection rules fired for this simulation.")
        lines.append("")

    anomaly = incident.get("anomaly_summary", {})
    lines.append("## Anomaly Detection")
    lines.append(f"- **Method:** {anomaly.get('method', 'n/a')}")
    lines.append(f"- **Anomaly flagged:** {anomaly.get('is_anomaly')}")
    lines.append(f"- **Anomaly score:** {anomaly.get('anomaly_score')}")
    if anomaly.get("explanations"):
        for ex in anomaly["explanations"]:
            lines.append(f"  - {ex}")
    lines.append("")

    lines.append("## Severity Reasoning")
    for r in incident.get("severity_reasoning", []):
        lines.append(f"- {r}")
    lines.append("")

    lines.append("## Potential Next-Stage Behaviour")
    lines.append(f"*{next_stage['disclaimer']}*")
    lines.append("")
    for b in next_stage["behaviours"]:
        lines.append(f"- {b}")
    if next_stage["supporting_sources"]:
        lines.append("")
        lines.append("Supporting knowledge base sources:")
        for s in next_stage["supporting_sources"]:
            lines.append(f"- {s['document']} — {s['section']} (relevance {s['relevance']})")
    lines.append("")

    lines.append("## Recommended Investigation Steps")
    for step in recommended_investigation_steps(scenario_key):
        lines.append(f"- {step}")
    lines.append("")

    lines.append("## Recommended Defensive Controls")
    for ctrl in recommended_defensive_controls(scenario_key):
        lines.append(f"- {ctrl}")
    lines.append("")

    lines.append("## AI Analyst Q&A Log")
    if qa_history:
        for qa in qa_history:
            lines.append(f"**Q ({qa['asked_at']}):** {qa['question']}")
            lines.append("")
            lines.append(qa["answer"])
            if qa.get("sources"):
                srcs = "; ".join(f"{s['document']} ({s['section']})" for s in qa["sources"])
                lines.append(f"\n*Sources: {srcs}*")
            lines.append("")
            lines.append("---")
    else:
        lines.append("No AI Analyst questions were asked during this investigation.")
    lines.append("")

    lines.append("## Limitations & Uncertainties")
    lines.append("- All data in this report is synthetic; findings reflect simulated "
                  "behaviour only and do not indicate a real-world compromise.")
    lines.append("- Detection rules are deterministic and scenario-scoped; they will not "
                  "catch patterns outside their defined conditions.")
    lines.append("- Anomaly detection is calibrated against a synthetic baseline "
                  "population, not a real historical baseline for this environment.")
    lines.append("- AI Analyst interpretations are grounded in the retrieved knowledge "
                  "base but should be verified against full investigation context before "
                  "acting on them.")

    return "\n".join(lines)


def generate_report_pdf_bytes(incident_id: str) -> bytes | None:
    """Best-effort PDF rendering of the markdown report using reportlab.
    Returns None if reportlab isn't installed — the UI falls back to the
    markdown download only in that case."""
    try:
        from io import BytesIO

        from reportlab.lib.pagesizes import LETTER
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
    except ImportError:
        return None

    md_text = generate_report_markdown(incident_id)
    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("H1", parent=styles["Heading1"], fontSize=16, spaceAfter=10)
    h2 = ParagraphStyle("H2", parent=styles["Heading2"], fontSize=13, spaceAfter=8, spaceBefore=10)
    body = ParagraphStyle("Body", parent=styles["BodyText"], fontSize=9.5, leading=13)

    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=LETTER,
                             leftMargin=0.7 * inch, rightMargin=0.7 * inch,
                             topMargin=0.6 * inch, bottomMargin=0.6 * inch)
    story = []
    for line in md_text.split("\n"):
        safe = (line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))
        if line.startswith("# "):
            story.append(Paragraph(safe[2:], h1))
        elif line.startswith("## "):
            story.append(Paragraph(safe[3:], h2))
        elif line.startswith("### "):
            story.append(Paragraph(f"<b>{safe[4:]}</b>", body))
        elif line.strip() == "" :
            story.append(Spacer(1, 4))
        elif line.strip() == "---":
            continue
        else:
            story.append(Paragraph(safe, body))
    doc.build(story)
    return buf.getvalue()


def recommended_investigation_steps(scenario_key: str) -> list[str]:
    common = ["Review the full event timeline for this incident in sequence."]
    per_scenario = {
        "credential_abuse": [
            "Verify authentication activity for the affected account and source IP.",
            "Confirm whether the account owner recognizes the successful session.",
            "Review the privilege request against change-management records.",
            "Review exactly what was accessed at the sensitive resource.",
        ],
        "malicious_file": [
            "Isolate the affected endpoint pending further analysis.",
            "Review the process tree and any files written by the process.",
            "Check the outbound destination against threat intelligence sources.",
            "Search for the same indicator on other endpoints.",
        ],
        "web_abuse": [
            "Review application logs for the full set of malformed requests.",
            "Confirm the unauthorized resource attempt was correctly denied.",
            "Check for input validation gaps the malformed input may have reached.",
            "Consider rate-limiting or blocking the source pending review.",
        ],
        "insider_threat": [
            "Review whether the accessed resources relate to the user's role.",
            "Correlate access timing with the user's normal working pattern.",
            "Identify the destination of the large data transfer.",
            "Escalate to management/HR through proper process before any action "
            "against the individual.",
        ],
    }
    return common + per_scenario.get(scenario_key, [])


def recommended_defensive_controls(scenario_key: str) -> list[str]:
    common = ["Continue monitoring the affected account/resource for further activity."]
    per_scenario = {
        "credential_abuse": [
            "Review authentication controls (MFA, lockout policy) for this account.",
            "Alert on future authentication from new sources for this account.",
            "Review privilege escalation approval workflow.",
        ],
        "malicious_file": [
            "Review email/attachment filtering rules for the observed pattern.",
            "Review endpoint detection rules for the observed process behaviour.",
            "Block the observed outbound destination if confirmed malicious.",
        ],
        "web_abuse": [
            "Review and strengthen input validation on the affected endpoints.",
            "Review authorization checks on administrative functionality.",
            "Add or tune rate-limiting for the affected endpoints.",
        ],
        "insider_threat": [
            "Review least-privilege assignment for the affected account.",
            "Review data-loss-prevention controls on the affected repositories.",
            "Review egress monitoring for large transfers to external destinations.",
        ],
    }
    return common + per_scenario.get(scenario_key, [])
